# Generated by Django 5.1.3 on 2024-12-09 17:43
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                (
                    'config_id', models.AutoField(
                        primary_key=True, serialize=False, unique=True,
                    ),
                ),
                ('name', models.CharField()),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('uptaded_at', models.DateTimeField()),
                ('config_string', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateField()),
                (
                    'related_content', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='scraper.content',
                    ),
                ),
                (
                    'related_ticker', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL, to='tickers.ticker',
                    ),
                ),
                (
                    'post_metadata', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='scraper.postmeta',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='postmeta',
            name='source',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.source',
            ),
        ),
    ]
