# Generated by Django 5.1.3 on 2026-03-01 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptaded_at', models.DateTimeField(auto_now=True)),
                ('config_string', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PostPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('prediction', models.PositiveSmallIntegerField()),
                ('probabilities', models.JSONField()),
                ('model_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('login_required', models.BooleanField(default=False)),
                ('credentials_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='scraper_con_created_85048c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('views', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shares', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.source')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(db_index=True)),
                ('related_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.content')),
                ('related_ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tickers.ticker')),
                ('post_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.postmeta')),
                ('post_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.postprediction')),
            ],
            options={
                'ordering': ['-time_stamp'],
                'indexes': [models.Index(fields=['related_ticker', 'time_stamp'], name='scraper_pos_related_0dba8f_idx')],
                'unique_together': {('related_ticker', 'time_stamp', 'related_content')},
            },
        ),
        migrations.AddConstraint(
            model_name='postmeta',
            constraint=models.CheckConstraint(condition=models.Q(('likes__gte', 0)), name='likes_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='postmeta',
            constraint=models.CheckConstraint(condition=models.Q(('views__gte', 0)), name='views_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='postmeta',
            constraint=models.CheckConstraint(condition=models.Q(('shares__gte', 0)), name='shares_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='postmeta',
            constraint=models.CheckConstraint(condition=models.Q(('comments__gte', 0)), name='comments_nonnegative'),
        ),
    ]
