# Generated by Django 5.1.3 on 2024-12-23 09:45
from __future__ import annotations

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPrediction',
            fields=[
                (
                    'prediction_id', models.AutoField(
                        primary_key=True, serialize=False,
                    ),
                ),
                ('prediction', models.IntegerField()),
                (
                    'propabilities', django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(
                        ), size=None, validators=[django.core.validators.MaxLengthValidator(3)],
                    ),
                ),
                ('prediction_model', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='uptaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_prediction',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='scraper.postprediction',
            ),
            preserve_default=False,
        ),
    ]
