# Generated by Django 5.1.3 on 2026-08-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_config_uptaded_at_config_updated_at_and_more'),
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('headline', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.postprediction')),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['ticker', 'published_at'], name='scraper_new_ticker__d77e27_idx')],
            },
        ),
    ]
