# Generated by Django 5.1.3 on 2024-12-23 10:07
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_postprediction_alter_config_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='source',
            name='base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='credentials_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
