# Generated by Django 5.1.3 on 2024-12-23 10:10
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_type_source_category_source_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
