services:
  # --- DATABASE
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # --- REDIS
  redis:
    image: redis:7-alpine

  # --- DJANGO API
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:z
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - selenium

  # --- LLM WORKER
  llm_worker:
    build: ./backend
    command: python manage.py run_llm_worker
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:z
    depends_on:
      - db
      - redis

  # --- FINNHUB NEWS INGESTOR
  finnhub_ingestor:
    build: ./backend
    command: python manage.py run_finnhub_ingestion
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:z
    depends_on:
      - db
      - redis

  # --- SELENIUM
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2g'
    env_file:
      - ./backend/.env
    environment:
      SE_VNC_PASSWORD: ${VNC_PASSWORD}
      SE_VNC_VIEW_ONLY: "true"
    ports:
      - "127.0.0.1:4444:4444"
      - "127.0.0.1:7900:7900"

  # --- FRONTEND
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_NOVNC_URL=http://localhost:7900
      - NEXT_PUBLIC_VNC_PASSWORD=${VNC_PASSWORD}
    depends_on:
      - api

volumes:
  postgres_data: