# Generated by Django 5.1.3 on 2024-12-09 17:43
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
        (
            'scraper',
            '0001_initial',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField()),
                ('symbol', models.CharField()),
                ('full_name', models.CharField()),
            ],
        ),
    ]
