# Generated by Django 5.1.3 on 2026-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=8, unique=True)),
                ('full_name', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['type', 'symbol'], name='tickers_tic_type_b8b88c_idx')],
            },
        ),
    ]
