# Generated by Django 5.1.3 on 2024-12-12 21:07
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='full_name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(unique=True),
        ),
    ]
