# Generated by Django 5.1.3 on 2026-08-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='full_name',
            field=models.CharField(max_length=128),
        ),
    ]
