# Generated by Django 5.1.3 on 2026-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=12, unique=True)),
                ('hashed_secret', models.CharField(max_length=64)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
