# Generated by Django 5.1.3 on 2026-03-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('signal_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('signal_type', models.CharField()),
                ('confidence_score', models.FloatField()),
                ('generated_at', models.DateTimeField()),
                ('used_model', models.CharField()),
                ('config_ig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.config')),
                ('ticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
        ),
    ]
