# Generated by Django 5.1.3 on 2024-12-12 21:07
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            'scraper',
            '0001_initial',
        ),
        ('tickers', '0002_alter_ticker_full_name_alter_ticker_symbol'),
        (
            'scraper',
            '0002_postprediction_alter_config_created_at_and_more',
        ),
        (
            'scraper',
            '0003_auto_20230901_1234',
        ),
        (
            'scraper',
            '0004_source_name',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                (
                    'signal_id', models.AutoField(
                        primary_key=True, serialize=False, unique=True,
                    ),
                ),
                ('signal_type', models.CharField()),
                ('confidence_score', models.FloatField()),
                ('generated_at', models.DateTimeField()),
                ('used_model', models.CharField()),
                (
                    'config_ig', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='scraper.config',
                    ),
                ),
                (
                    'ticker_id', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker',
                    ),
                ),
            ],
        ),
    ]
