# Generated by Django 5.1.3 on 2026-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='signal',
            name='used_model',
            field=models.CharField(max_length=64),
        ),
    ]
