# Generated by Django 5.1.3 on 2026-04-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_config_uptaded_at_config_updated_at_and_more'),
        ('signals', '0002_alter_signal_generated_at_alter_signal_signal_type_and_more'),
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='config_ig',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='ticker_id',
            new_name='ticker',
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['generated_at'], name='signals_sig_generat_5cf9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['ticker', 'generated_at'], name='signals_sig_ticker__84cd7f_idx'),
        ),
    ]
