# Generated by Django 5.1.3 on 2026-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_rename_config_ig_signal_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='signals/uploaded_files/')),
                ('is_interviewer_visible', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
